Zona import Zona
class Animal(Zona):
    totalAnimales=0
    def __init__(self,nombre,edad,habit,genero,zona):
        _nombre= nombre
        _edad= edad
        _habit=habit
        _genero= genero
        _zona= zona
    def movimiento(self):
    def totalPorTipo(self):
    def __str__(self):
class Mamifero(Animal):
    def __init__(self,listado,caballos,leones,pelaje,patas):
        _listado= listado
        _caballos= caballos
        _leones= leones
        _pelaje= pelaje
        _patas= patas
    def cantidadMamiferos(self):
    def crearCaballo(self):
    def crearLeon(self):
class Ave(Animal):
    def __init__(self,listado,halcones,aguilas,colorPlumas):
        _listado= listado
        _halcones= halcones
        _aguilas= aguilas
        _ColorPlumas= colorPlumas
    def cantidadAves(self):
    def movimiento(self):
    def crearHalcon(self):
    def crearAguila(self):
class Reptil(Animal):
    def __init__(self,listado,iguanas,serpientes,colorEscamas,largoCola):
        _listado= listado
        _iguanas= iguanas
        _colorEscamas= colorEscamas
        _serpientes= serpientes
        _largoCola=largoCola
    def cantidadReptiles(self):
    def movimiento(self):
    def crearIguana(self):
    def crearSerpiente(self):
class Pez(Animal):
    def __init__(self,listado,salmones,bacalaos,colorEscamas,cantidadAletas):
        _listado= listado
        _salmones= salmones
        _bacalaos= bacalaos
        _colorEscamas= colorEscamas
        _cantidadAletas= cantidadAletas
    def cantidadPeces(self):
    def movimiento(self):
    def crearIguana(self):
    def crearSerpiente(self):
class Anfibio(Animal):
    def __init__(self,listado,ranas,salamandras,colorPiel,venenoso):
        _listado= listado
        _ranas= ranas
        _salamandras= salamandras
        _colorPiel= colorPiel
        _venenoso= venenoso
    def cantidadAnfibios(self):
    def movimiento(self):
    def crearRana(self):
    def CrearSalamandra(self):